### ISSUE TITLE
Push the latest gem version to Github

### ISSUE THREAD

**Issue by stengland** [sergio-fry/huginn_ruby_agent#1]
Hi @sergio-fry,

Could you push the latest version of the gem to github. Finding this gem very useful and would like to contribute if possible.

Cheers,
Steve

**Comment by sergio-fry** [comment]
@stengland it is already the latest version. What do you mean?

**Comment by sergio-fry** [comment]
@stengland I see now: only version 0.1 was pushed. Updated!

**Comment by sergio-fry** [comment]
@stengland I have refactored code and wrote some specs for it. Also ability to access credentials added.
